[package]
name = "core_highlight"
version = "0.1.0"
edition = "2021"

[dependencies]
core_types = { path = "../core_types" }
tree-sitter = "0.24"
tree-sitter-javascript = "0.23"
tree-sitter-typescript = "0.23"
