[package]
name = "core_api"
version = "0.1.0"
edition = "2021"

[dependencies]
core_types = { path = "../core_types" }
core_fs = { path = "../core_fs" }
core_highlight = { path = "../core_highlight" }

[dev-dependencies]
tempfile = "3"
